version: 2
jobs:
  build:
    working_directory: /go/src/github.com/livepeer/lpms
    docker:
      - image: "circleci/golang:1.15.15"
        environment:
          GOROOT: /usr/local/go
          PKG_CONFIG_PATH: "/home/circleci/compiled/lib/pkgconfig"
          # compile ffmpeg with tools required for tests
          BUILD_TAGS: "debug-video"
          # required for libx265 support (software) for running tests on CI
          LD_LIBRARY_PATH: "/home/circleci/compiled/lib"
    steps:
      - checkout

      - run:
          name: "Get latest install_ffmpeg.sh from go-livepeer"
          command: |
            rm install_ffmpeg.sh || true
            wget https://raw.githubusercontent.com/livepeer/go-livepeer/master/install_ffmpeg.sh

      - restore_cache:
          key: ffmpeg-cache-{{ checksum "install_ffmpeg.sh" }}

      - run:
          name: "Tweak PATH"
          command: |
            echo 'export PATH=/home/circleci/compiled/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: "Build FFMpeg"
          command: |
            sudo apt-get update
            sudo apt-get install -y autoconf build-essential pkg-config autoconf gnutls-dev zlib1g-dev netcat-openbsd xxd clang
            bash ./install_ffmpeg.sh

      - save_cache:
          paths:
            - "/home/circleci/nasm"
            - "/home/circleci/x264"
            - "/home/circleci/x265"
            - "/home/circleci/libvpx"
            - "/home/circleci/ffmpeg"
            - "/home/circleci/compiled"
          key: ffmpeg-cache-{{ checksum "install_ffmpeg.sh" }}

      - run:
          name: "Build LPMS"
          command: |
            go get ./cmd/example
            go build cmd/example/*.go
            bash test.sh
